---
title: "Course Project 2 - NOAA Storm Data"
author: "bthomas"
date: "February 13, 2016"
output: html_document
---

This document is response to the Coursera course project 2 assignment.

# Instructions
## Introduction

Storms and other severe weather events can cause both public health and economic problems for communities and municipalities. Many severe events can result in fatalities, injuries, and property damage, and preventing such outcomes to the extent possible is a key concern.

This project involves exploring the U.S. National Oceanic and Atmospheric Administration's (NOAA) storm database. This database tracks characteristics of major storms and weather events in the United States, including when and where they occur, as well as estimates of any fatalities, injuries, and property damage.

## Synopsis

- TBD
- TBD

## Data Processing

The data for this assignment come in the form of a comma-separated-value file compressed via the bzip2 algorithm to reduce its size. You can download the file from the course web site:

    [Storm Data [47Mb]](https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2)

Database documentation is available through the 2 links below. The documents below will provide information on variable construction and definition.

    [National Weather Service Storm Data Documentation](https://d396qusza40orc.cloudfront.net/repdata%2Fpeer2_doc%2Fpd01016005curr.pdf)
    [National Climatic Data Center Storm Events FAQ](https://d396qusza40orc.cloudfront.net/repdata%2Fpeer2_doc%2FNCDC%20Storm%20Events-FAQ%20Page.pdf)

The events in the database start in the year 1950 and end in November 2011. In the earlier years of the database there are generally fewer events recorded, most likely due to a lack of good records. More recent years should be considered more complete.

The code below was used to download the Storm Data to a data directory. It sets the working directory, cleans up the Global Environment, checks to see if the compressed data file was downloaded, downloads it if it has not been, checks for the unzipped file, checks to determine if it was not extracted, and it has not, it extracts the data file.

```{r, comment="Data Processing"}
# clean the global environment
rm(list = ls())
# set the working directory to the Course-Project-1 director
setwd("~/Documents/Coursera/Reproducable-Research/Course-Project-2")

# check to see if the file has been downloaded, if not, download the file
if (!file.exists("./Data/repdata_data_StormData.csv.bz2")) {
  download.file("https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2", "./Data/repdata_data_StormData.csv.bz2", method = "curl")
  
}

# check to see if the archives.csv exists, if not, extract it
if (!file.exists("./Data/repdata_data_StormData.csv")) {
  unzip("./Data/repdata_data_StormData.csv.bz2", exdir = "./Data/")
  
}
```
